[package]
name = "frack"
version = "2.0.0"
edition = "2021"

license = "MIT"
description = "A fake Rust error generator."
authors = ["Kyllingene"]

keywords = ["error", "diagnostic", "rustc"]
categories = ["command-line-utilities", "command-line-interface"]
